"use client";

import { routes } from "@/lib/routes";

// Define the sidebar structure for the Admin user type
export const AdminSidebarData = [
    {
        tittle: "Radar",
        icon: "airplay",
        showAsTab: true,
        separateRoute: false,
        submenuItems: [
            {
                label: "Dashboard",
                link: routes.dashboard,
                submenu: false,
                icon: "layout-dashboard",
                base: "dashboard",
                submenuItems: [],
            },
            {
                label: "Reports",
                link: routes.reports,
                submenu: false,
                icon: "report",
                base: "reports",
                submenuItems: [],
            },
        ],
    },
    {
        tittle: "Authentication",
        icon: "airplay",
        showAsTab: true,
        separateRoute: false,
        submenuItems: [
            {
                label: "Manage Users",
                link: routes.users,
                submenu: false,
                icon: "user",
                base: "users",
                submenuItems: [],
            },
            {
                label: "Roles & Permissions",
                link: routes.rolesPermissions,
                submenu: false,
                icon: "user-shield",
                base: "roles-permissions",
                submenuItems: [],
            },
        ],
    },
    {
        tittle: "Activities",
        icon: "airplay",
        showAsTab: true,
        separateRoute: false,
        submenuItems: [
            {
                label: "Bookings",
                link: routes.appointments,
                submenu: false,
                icon: "calendar-check",
                base: "appointments",
                submenuItems: [],
            },
            {
                label: "Registration",
                link: routes.registration,
                submenu: false,
                icon: "file-pencil",
                base: "registration",
                submenuItems: [],
            },
            {
                label: "Consultations",
                link: routes.consultations,
                submenu: false,
                icon: "stethoscope",
                base: "consultations",
                submenuItems: [],
            },
            {
                label: "Procedures",
                link: routes.procedures,
                submenu: false,
                icon: "report-medical",
                base: "procedures",
                submenuItems: [],
            },
            {
                label: "Diagnostics",
                link: routes.diagnostics,
                submenu: false,
                icon: "clipboard-heart",
                base: "diagnostics",
                submenuItems: [],
            },
            {
                label: "Imaging",
                link: routes.imaging,
                submenu: false,
                icon: "photo-scan",
                base: "imaging",
                submenuItems: [],
            },
            {
                label: "Clinical Services",
                link: routes.clinicalServices,
                submenu: false,
                icon: "building-hospital",
                base: "clinical-services",
                submenuItems: [],
            },
            {
                label: "Nurse Allocation",
                link: routes.nurses,
                submenu: false,
                icon: "home-exclamation",
                base: "nurses",
                submenuItems: [],
            },
            {
                label: "Accommodation",
                link: routes.accommodation,
                submenu: false,
                icon: "bed",
                base: "accommodation",
                submenuItems: [],
            },
            {
                label: "Billing",
                link: routes.billing,
                submenu: false,
                icon: "coin",
                base: "billing",
                submenuItems: [],
            },
            {
                label: "Documents",
                link: routes.documents,
                submenu: false,
                icon: "file-stack",
                base: "documents",
                submenuItems: [],
            },
            {
                label: "Messaging",
                link: routes.chat,
                submenu: false,
                icon: "message-dots",
                base: "chat",
                submenuItems: [],
            },
            {
                label: "Settings",
                link: routes.settings,
                submenu: false,
                icon: "user-cog",
                base: "settings",
                submenuItems: [],
            },
        ],
    },
    {
        tittle: "Setup",
        icon: "airplay",
        showAsTab: true,
        separateRoute: false,
        submenuItems: [
            {
                label: "Manage Accounts",
                link: "#",
                submenu: true,
                icon: "users-group",
                base: "manage-accounts",
                submenuItems: [
                    { label: "Patients", link: routes.patients },
                    { label: "Providers", link: routes.providers },
                    { label: "Nurses", link: routes.nurses },
                    { label: "Technicians", link: routes.technicians },
                ],
            },
            {
                label: "Manage Departments",
                link: routes.departments,
                submenu: false,
                icon: "building-community",
                base: "departments",
                submenuItems: [],
            },
            {
                label: "Manage Specialties",
                link: routes.specialties,
                submenu: false,
                icon: "star",
                base: "specialties",
                submenuItems: [],
            },
            {
                label: "Coding Master",
                link: routes.codingMaster,
                submenu: false,
                icon: "code",
                base: "coding-master",
                submenuItems: [],
            },
            {
                label: "Manage Resources",
                link: routes.resources,
                submenu: false,
                icon: "box",
                base: "resources",
                submenuItems: [],
            },
            {
                label: "Availability",
                link: "#",
                submenu: true,
                icon: "calendar-time",
                base: "availability",
                submenuItems: [
                    { label: "Resources", link: `${routes.availability}/resources` },
                    { label: "Providers", link: `${routes.availability}/providers` },
                    { label: "Nurses", link: `${routes.availability}/nurses` },
                    { label: "Technicians", link: `${routes.availability}/technicians` },
                    { label: "Working Hours", link: `${routes.availability}/working-hours` },
                    { label: "Holidays", link: `${routes.availability}/holidays` },
                    { label: "Vacations", link: `${routes.availability}/vacations` },
                    { label: "Commitments", link: `${routes.availability}/commitments` },
                    { label: "Exceptions", link: `${routes.availability}/exceptions` },
                ],
            },
        ],
    },
    {
        tittle: "Master Data",
        icon: "airplay",
        showAsTab: true,
        separateRoute: false,
        submenuItems: [
            {
                label: "Shift Master",
                link: routes.shifts,
                submenu: false,
                icon: "clock-hour-4",
                base: "shifts",
                submenuItems: [],
            },
            {
                label: "States",
                link: routes.masterStates,
                submenu: false,
                icon: "map-pin",
                base: "master-states",
                submenuItems: [],
            },
            {
                label: "Cities",
                link: routes.masterCities,
                submenu: false,
                icon: "building-arch",
                base: "master-cities",
                submenuItems: [],
            },
        ],
    },
];
